kind = "web"
previewPath = "/"
title = "Nicemp Ferramentas"
version = "1.0.0"
id = "artifacts/nicemp"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21620

[services.development]
run = "pnpm --filter @workspace/nicemp run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nicemp", "run", "build" ]
publicDir = "artifacts/nicemp/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21620"
BASE_PATH = "/"
