export const routes = {
  home: "/",
  toolsHome: "/ferramentas",
  login: "/entrar",
  signUp: "/criar-conta",
  authCallback: "/auth/callback",
  completeCpf: "/completar-cpf",
  academy: "/aprenda",
  academyArticle: "/aprenda/:slug",
  manage: "/gerencie",
  manageDre: "/gerencie/dre",
  manageCashflow: "/gerencie/fluxo-de-caixa",
  manageIndicators: "/gerencie/indicadores",
  admin: "/admin",
  solutions: "/#solucoes",
  plans: "/#planos",
  about: "/#sobre",
  privacy: "/politica-de-privacidade",
  terms: "/termos-de-uso",
  roi: "/roi",
  markup: "/markup",
  simplesNacional: "/impostos/simples-nacional",
} as const;
